### ISSUE TITLE
Configurable snapshot count

### ISSUE THREAD

**Issue by Yamakaky** [csirac2/snazzer#25]
It should be possible to configure how many snapshots are kept.

**Comment by csirac2** [comment]
Duplicate of issue #22.

Thanks for reporting. This is a commonly requested feature, I'll get to it shortly. In the meantime I usually have something like

```
. /etc/default/snazzer && snazzer
```

This loads the `SNAZZER_` envs with the desired snapshot retention settings.

**Comment by Yamakaky** [comment]
Ok

**Comment by csirac2** [comment]
Check https://github.com/csirac2/snazzer/blob/master/doc/examples/etc/default/snazzer for example envs
