### ISSUE TITLE
Install zipped manpages to $INSTALL_PREFIX/share/man

### ISSUE THREAD

**Issue by florianjacob** [csirac2/snazzer#35]
It would ease creating and maintaining snazzer packages if `make install` would also install the manpages to `$INSTALL_PREFIX/share/man`, preferably gzipped.

Refer to the [AUR package shell script](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=snazzer-git) to see what package maintainers are currently doing.

I don't know how to achieve that, though. Add another find statement to make install / uninstall somehow?

This was requested by maintainer jhass @ https://aur.archlinux.org/packages/snazzer-git/

**Comment by csirac2** [comment]
INSTALL_PREFIX should never have been a full path to bin/ ... to avoid another similar mistake I'm doing this next fix as a PR & inviting code review ;-)

Changing INSTALL_PREFIX semantics is a breaking change, so a heads up to @jhass would be good

**Comment by florianjacob** [comment]
Let's do this. :+1:

**Comment by florianjacob** [comment]
I'll reach out to @jhass as soon as the PR is ready and coordinate the merge. I think he lives in UTC+1 as well, so we can probably figure something out to make the timeframe in which the build would break quite short.

**Comment by csirac2** [comment]
Ready to go I think, will let you merge when ready.

**Comment by florianjacob** [comment]
#36 works like charm! :sparkles:
