### ISSUE TITLE
exclude mountpoint / root volume from being snapshotted

### ISSUE THREAD

**Issue by florianjacob** [csirac2/snazzer#38]
Correct me if I'm wrong, but I think there's no option currently to exclude the root volume a.k.a. the mountpoint from being snapshotted. The exclude patterns file only applies to subvolumes, and as they don't have a leading `/` one couldn't specify the root to be excluded at all.

I like to have a somewhat flat subvolume layout, where a subvolume of the root volume is mounted as `/`, not the root volume itself, while the root volume is only used to contain the other subvolumes, but not mounted in the filesystem hierarchy.
See https://btrfs.wiki.kernel.org/index.php/SysadminGuide#Layout for more details so I don't have to repeat them here. :wink:

I'm not sure what to do here, though. Options that came to my mind, in no particular order:
- add a command line option like `snazzer --ignore-mountpoint`
- prefix all subvolumes listed by `btrfs subvolume list -t` with a `/`, so that one's able to specify `/` in the snazzer exclude file. This would require a change in all absolute paths in the exclude file, but might improve usability as people would probably throw in the leading `/` anyway if they're not familiar with the format of `sudo btrfs subvolume list`.
- Do nothing at all and just accept that there's an unneeded `/.snapshotz` full of snapshots that never change at all.

I'm currently using my own fork that has mounpoint snapshotting disabled in the code, but that's no general solution, of course. :wink:

**Comment by csirac2** [comment]
I'd prefer your second option - prefix exclude patterns with a /

I really should've tagged snazzer before we started making breaking changes. Perhaps I'll do that before we introduce this change.

Perhaps we can exit with error if an exclude pattern line does not begin with a /

**Comment by florianjacob** [comment]
Yeah, :+1: for tagging a 0.1.0 release before we do any other breaking changes. :wink:

Exiting for lines not starting with a / or \* seems like a good idea to catch errors.

**Comment by florianjacob** [comment]
I was able to generalize the handling of do_mountpoint, the mountpoint is now returned with list_subvolumes as well, so it hasn't to be handled separately. See PR #41.
