### ISSUE TITLE
documentation clarification: does snazzer-receive do snazzer --prune as well?

### ISSUE THREAD

**Issue by florianjacob** [csirac2/snazzer#46]
I'm currently in the process of restoring a snazzer snapshot for each subvolume from my external backup disk to my internal main disk, as the filesystem got corrupted beyond repair.

So what will happen the next time I run snazzer-receive to get new snapshots from my internal disks, which has none of the old snapshots prior to the corruption? Will the old snapshots be deleted from the external disk, or does snazzer-receive never change snapshots already transfered, and I have to actually run snazzer --prune on the external hard disk as well, from time to time?

From my studies of snazzer-receive source code I now guess it's the second option, but I did not find any statements regarding this in the manpages.

@csirac2 I can get a PR ready improving the manpages as soon as this is clarified, if you want. :)

**Comment by csirac2** [comment]
It's the latter, correct. I used to have snazzer involved in multi-tier staging of backups: onsite media would be occasionally synced with offsite media, so I wanted the pruning of each stage to be flexible. I hope your backups were ok!

**Comment by csirac2** [comment]
Also I'd love to hear your thoughts on how a snazzer-restore would work. I have a snazzer-receive.bats test suite in a branch somewhere I'll try to finish up asap.

**Comment by florianjacob** [comment]
My backups seem to be allright, would have prefered to test them as a test, though. 😆

Having pruning separated helps me in my case, as I don't have to fear all the backup history is deleted the next time I attach my external disk. :+1:

This is what I did trying to solve this:
 * Recreate a btrfs filesystem
 * Recreate my subvolumes and `.snapshotz` directories
 * Use `btrfs send | btrfs receive` to transfer the latest snapshots into the new `.snapshotz` directories
 * Note that this doesn't work, because I can't do `btrfs snapshot` on the latest snapshot to recreate the actual subvolume, as those are _inside_ the subvolume
 * Copy the latest snapshot to a place outside of the subvolume with `btrfs snapshot`
 * Delete the created subvolumes
 * Do another snapshot to get it in place.
 * Delete the temporary snapshot
 * Boot the system
 * Note that snazzer does not do new snapshots anymore
 * Delete the `.snapshot-measurements.exclude` files that were preventing the restored subvolumes from being snapshotted.

This got me a working system, the only thing changed before & after the incident is now that I don't have any snapshots from before the incident on the internal main disk.

Now that I see the issue with the snapshotz-inside-the-subvolume issue, I think I still can't do it with a temporary snapshot, as btrfs send | btrfs receive seem to only store the target subvolume under the same name as the source subvolume.

A simple but very useful snazzer-restore would take the latest snapshot of a subvolume and restore it at another device, and delete the .snapshot-measurements.exclude file, as that could easily be forgotten and the non-working snazzer backups might go unnoticed.

Additionally, I'd have used a kind of reverse snazzer-receive feature which syncs back the snapshot history to the main device. I can't do that currently, can I?

With that, I envision the ideal workflow to be something like „do a backup on your external disk, detach it, a few moments later the internal disks explodes, buy a new disk, run snazzer-restore -all and the internal disk is in the same state as before the backup.“, and snazzer would be the best backup tool ever made. ✨  😄 

I'm currently thinking about having a snapshotz subvolume besides the subvolume being snapshotted and mount that to subvolume/.snapshotz via fstab. This way, one could easily throw away the main subvolume and let an older snapshot take its place, e.g. for cases where one messed up the OS and wants to restore a previous state. This would solve the snapshots-are-always-inside-the-subvolume-being-snapshotted problem, but come at the cost of a very verbose fstab…

**Comment by florianjacob** [comment]
Filesystem Corruption Post-Mortem: Ditching snapper + irregular copies to external drives and deploying snazzer instead just a few weeks ago already saved me from many many hours of work and pain to get everything back in a usable state, and from quite a number of lost files.

Thumbs up for you & snazzer! 👍
