### ISSUE TITLE
snazzer-receive throws "ERROR: unable to resolve -p" with btrfs-progs 4.11

### ISSUE THREAD

**Issue by ntxy** [csirac2/snazzer#53]
btrfs-progs 4.11 changed the options parser. Now snazzer throws errors.

line 178 in snazzer-receive throws: "ERROR: unable to resolve -p"
`  $SUDO btrfs send "$SNAP_ABSPATH" -p "$SNAP_PARENT_PATH" | \
                $SUDO btrfs receive "$DEST_SUBVOL/.snapshotz/.incomplete"`

has to do with some command line argument parsing.

man btrfs send sais this:
`btrfs send [-ve] [-p <parent>] [-c <clone-src>] [-f <outfile>] <subvol>
       [<subvol>...]`

so I put line 178 the other way arround:
`$SUDO btrfs send -p "$SNAP_PARENT_PATH" "$SNAP_ABSPATH"  | ....`

...and it works.

btrfs-progs 4.11-1

with btrfs-progs 4.9.1 there is no problem.

or should I report to btrfs-progs ?

**Comment by csirac2** [comment]
Wow, that's really interesting. I think they would appreciate a bug report that there is a regression in their opts parser: optional arguments are rarely also positional... I'll mark this as a bug and we can change the invocation for the next version of snazzer. Thanks!

**Comment by ntxy** [comment]
for reference, the snazzer way of calling btrfs send "should never have been valid" 
[btrfs-progs issue](https://github.com/kdave/btrfs-progs/issues/47)

**Comment by csirac2** [comment]
Thanks for chasing this up. We'd better address this and do a new release soon.

**Comment by csirac2** [comment]
If you have a chance to test, I've got a PR to fix this in #54 - it also updates the dry-run output and snazzer-send wrapper.
